name: e2e tests

on:
  push:
    branches:
      - '**'

jobs:
  percy_tests:
      name: e2e tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout files
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install packages
          run: yarn install
        - name: Run tests
          run: yarn wdio
          env:
              BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
              BROWSERSTACK_ACCESS_KEY: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
